package com.banking.gateway.security;

import io.jsonwebtoken.Claims;
import io.jsonwebtoken.Jwts;
import io.jsonwebtoken.security.Keys;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Component;

import javax.crypto.SecretKey;
import java.util.Base64;
import java.util.Date;

// Gateway-side JWT utility — validation only, no DB access, no token generation.
// Token generation lives in user-service; the shared secret must match.
@Component
public class JwtUtil {

    @Value("${jwt.secret}")
    private String secret;

    private SecretKey getSigningKey() {
        byte[] keyBytes = Base64.getDecoder().decode(secret);
        return Keys.hmacShaKeyFor(keyBytes);
    }

    // Parses and returns all claims. Throws if signature is invalid or token is malformed.
    public Claims extractAllClaims(String token) {
        return Jwts.parser()
                .verifyWith(getSigningKey())
                .build()
                .parseSignedClaims(token)
                .getPayload();
    }

    // Subject is the user's email — set during token generation in user-service.
    public String extractEmail(String token) {
        return extractAllClaims(token).getSubject();
    }

    // "role" claim is added by user-service during login (e.g. "USER" or "ADMIN").
    // Returns null if the claim is absent (tokens generated by the monolith).
    public String extractRole(String token) {
        return extractAllClaims(token).get("role", String.class);
    }

    // "userId" claim is added by user-service during login.
    // Returns null if the claim is absent (tokens generated by the monolith).
    public String extractUserId(String token) {
        Object userId = extractAllClaims(token).get("userId");
        return userId != null ? userId.toString() : null;
    }

    public boolean isTokenExpired(String token) {
        return extractAllClaims(token).getExpiration().before(new Date());
    }
}
